name = "yoganjali-studio"
main = "src/worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "yoganjaliyoga.com/*", zone_name = "yoganjaliyoga.com" },
  { pattern = "www.yoganjaliyoga.com/*", zone_name = "yoganjaliyoga.com" }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "yoganjali_db"
database_id = "8ed50252-395f-4698-8895-7f604122ae31"
