name = "yoganjali-studio"
main = "src/worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "yoganjaliyoga.com/*", zone_name = "yoganjaliyoga.com" },
  { pattern = "www.yoganjaliyoga.com/*", zone_name = "yoganjaliyoga.com" }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

